### ISSUE TITLE
Searching for "bencode" on pypi doesn't find bcoding

### ISSUE THREAD

**Issue by conquerist** [flying-sheep/bcode#8]
The bcoding package is a little hard to find, because [searching for "bencode"](https://pypi.python.org/pypi?%3Aaction=search&term=bencode&submit=search) on pypi doesn't list "bcoding" in the search results. Adding the term "bencode" to the summary, keywords, or description fields on pypi may make the package easier to find.

**Comment by flying-sheep** [comment]
fixed, thanks for the pointer
